### ISSUE TITLE
Bug? Import on deno throw 404

### ISSUE THREAD

**Issue by dareksob** [josh-hemphill/valivar#3]
Deno : 1.7.8

code line
import valivar from "https://deno.land/x/valivar@v6.2.9/mod.ts";

throw error
error: Import 'https://deno.land/x/valivar@v6.2.9/dist/valivar.esm.js' failed: 404 Not Found

**Comment by josh-hemphill** [comment]
Somehow the dist folder got removed in deno.land... It seems to be present on both NPM and github, so not sure how that happened. Working on fixing.

**Comment by josh-hemphill** [comment]
It's working now. Also improved my whole release process while I was at it. Hopefully I can track everything better now if it happens again.
